### ISSUE TITLE
Cannot declare AsyncSession outside event loop

### ISSUE THREAD

**Issue by mavic111** [yifeikong/curl_cffi#117]
In httpx, i can declare AsyncClient outside event loop.

```python
import asyncio
from curl_cffi.requests import AsyncSession
from httpx import AsyncClient

client = AsyncClient(http2=True)
# client = AsyncSession()

async def foo():
    data = {
        'foo': 'bar'
    }
    res = await client.get('https://httpbin.org/cookies/set', params=data)
    print(res.cookies)


async def bar():
    data = {
        'bar': 'foo'
    }
    res = await client.get('https://httpbin.org/cookies/set', params=data)
    print(res.cookies)


async def main():
    await asyncio.gather(foo(), bar())
    print(client.cookies)


asyncio.run(main())
```

But if i'm using AsyncSession from curl_cffi, it crash.

```bash
Traceback (most recent call last):
  File "C:\Users\muham\experiment\async_test.py", line 6, in <module>
    client = AsyncSession()
             ^^^^^^^^^^^^^^
  File "C:\Users\muham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\blegping-R3zLSmhu-py3.11\Lib\site-packages\curl_cffi\requests\session.py", line 605, in __init__
    self.loop = loop if loop is not None else asyncio.get_running_loop()
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
```

**Comment by yifeikong** [comment]
There is no reason to put `get_running_loop` inside `__init__`, it should be moved out in the future. Once done, you can create a new instance out of async function.
