### ISSUE TITLE
Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by r00t-Taurus** [yifeikong/curl_cffi#128]
I used v0.5.9b5, python 3.11.5

I use `async with requests.AsyncSession(max_clients=10000) as sess:`
Just sending out requests and at some point in time I get this error 
everything is fine on version 0.5.7
```
Fatal Python error: Segmentation fault
Current thread 0x00007f64746e9b80 (most recent call first):
File "/usr/local/lib/python3.11/site-packages/curl_cffi/aio.py", line 139 in socket_action
File "/usr/local/lib/python3.11/site-packages/curl_cffi/aio.py", line 148 in process_data
File "/bot/app/misc/parser_essintials.py", line 531 in wrapper_for_run_cpu_bound
File "/usr/local/lib/python3.11/concurrent/futures/process.py", line 256 in _process_worker
File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108 in run
File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314 in _bootstrap
File "/usr/local/lib/python3.11/multiprocessing/popen_fork.py", line 71 in _launch
File "/usr/local/lib/python3.11/multiprocessing/popen_fork.py", line 19 in init
File "/usr/local/lib/python3.11/multiprocessing/context.py", line 281 in _Popen
File "/usr/local/lib/python3.11/multiprocessing/process.py", line 121 in start
File "/usr/local/lib/python3.11/concurrent/futures/process.py", line 764 in _spawn_process
File "/usr/local/lib/python3.11/concurrent/futures/process.py", line 754 in _launch_processes
File "/usr/local/lib/python3.11/concurrent/futures/process.py", line 727 in _start_executor_manager_thread
File "/usr/local/lib/python3.11/concurrent/futures/process.py", line 788 in submit
```

```
Future exception was never retrieved
future: <Future finished exception=BrokenProcessPool('A process in the process pool was terminated abruptly while the future was running or pending.') created at /usr/local/lib/python3.11/asyncio/futures.py:417>
```

```
def wrapper_for_run_cpu_bound(func, *args, **kwargs):
    new_loop = uvloop.new_event_loop()
    new_loop.slow_callback_duration = 0.800
    asyncio.set_event_loop(new_loop)
    new_loop.run_until_complete(func(*args, **kwargs))

```

**Comment by yifeikong** [comment]
Does it always happen or only occasionaly?  If always, post a standalone code snippet so I can reproduce it. If occasionaly, try to increase the ulimit as shown in this [post](https://stackoverflow.com/questions/10035541/what-causes-a-python-segmentation-fault). Again, I think `max_clients=10000` might be too big here, but it depends on your hardware, though.

**Comment by r00t-Taurus** [comment]
With version v0.5.9b5 it always happens, at first it works fine for a while, then I get this error, but if you change the version to v0.5.7 there is no such error

**Comment by yifeikong** [comment]
It seems that you are using multiprocessing, do you mind sharing the full snippet?

**Comment by r00t-Taurus** [comment]
I've tried to reproduce the bug but no luck, it only appears under load, can you tell me what I can do to catch this bug and I'll do it, here's the sample code
```
import asyncio
from concurrent.futures import ProcessPoolExecutor
from contextlib import suppress

import uvloop
from curl_cffi import requests


pool_process = ProcessPoolExecutor()

_running_tasks = set()


async def run_processing_tasks(n, *coros):
    semaphore = asyncio.Semaphore(n)

    async def sem_coro(coro):
        try:
            async with semaphore:
                return await coro
        except asyncio.CancelledError:
            coro.close()

    tasks = []

    for coro in coros:
        task = asyncio.create_task(sem_coro(coro))
        _running_tasks.add(task)
        task.add_done_callback(_running_tasks.discard)
        tasks.append(task)

    results = []

    for task in tasks:
        with suppress(asyncio.CancelledError):
            results.append(await task)

    return results


async def send_req(url, sess):
    item = await sess.get(
        url,
        impersonate="safari15_5",
        timeout=6,
    )
    print(item.status_code)


async def make_req(url_list):
    async with requests.AsyncSession(max_clients=10000) as sess:
        await run_processing_tasks(
            60,
            *(send_req(url, sess) for url in url_list),
        )


def wrapper_for_run_cpu_bound(func, *args, **kwargs):
    new_loop = uvloop.new_event_loop()
    new_loop.slow_callback_duration = 0.800
    asyncio.set_event_loop(new_loop)
    new_loop.run_until_complete(func(*args, **kwargs))


async def main():
    for _ in range(50): 
        asyncio.get_running_loop().run_in_executor(
            pool_process,
            wrapper_for_run_cpu_bound,
            make_req,
            ["https://www.google.com/"] * 300,
        )


if __name__ == "__main__":
    uvloop.install()
    asyncio.run(main(), debug=True)

```

**Comment by yifeikong** [comment]
The code is fine on my side, too. Although I think that the `loop.run_in_executor` part is actually `PoolExecutor.submit`, no asyncio involved in creating processes.

I tried to limit memory with:

```
systemd-run --scope -p MemoryMax=200M python segfault.py
```

The following error occurs:

```
exception calling callback for <Future at 0x7fea897e8c80 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 342, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.10/asyncio/futures.py", line 399, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "uvloop/loop.pyx", line 1288, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 671, in uvloop.loop.Loop._append_ready_handle
  File "uvloop/loop.pyx", line 703, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed
```

However, it's still not SegmentationFault.

**Comment by r00t-Taurus** [comment]
What can I do to catch this bug? What information can I provide? I forgot to mention that it runs under venv and docker.

**Comment by yifeikong** [comment]
venv and docker should not be related to the issue you described. I just checked the diff, there are no significant changes related to asyncio. The only thing I noticed that is a bugfix -- previously, when exceptions are raised, the curl instance will be lost, resulting in hanging  if there are enough exceptions, which might be covered by a large number of `max_clients`.

```diff
# in requests/session.py
         try:
             # curl.debug()
             await self.acurl.add_handle(curl)
             # print(curl.getinfo(CurlInfo.CAINFO))
-            curl.clean_after_perform()
         except CurlError as e:
-            raise RequestsError(e)
-        rsp = self._parse_response(curl, req, buffer, header_buffer)
-        curl.reset()
-        self.push_curl(curl)
-        return rsp
+            rsp = self._parse_response(curl, buffer, header_buffer)
+            rsp.request = req
+            raise RequestsError(str(e), e.code, rsp) from e
+        else:
+            rsp = self._parse_response(curl, buffer, header_buffer)
+            rsp.request = req
+            return rsp
+        finally:
+            curl.reset()
+            self.push_curl(curl)
```

Notice that the last 2 lines were moved into `finally` to ensure they are always executed. You can try to restore the previous **wrong** behavior by moving them out of `finally` and see if your issue goes away.

**Comment by r00t-Taurus** [comment]
I think I've managed to make an example, error occurs when cancel_processing_tasks is executed

```
import asyncio
import random
from concurrent.futures import ProcessPoolExecutor
from contextlib import suppress
import logging

import uvloop
from curl_cffi import requests

logging.basicConfig(level=logging.DEBUG)

pool_process = ProcessPoolExecutor()
_running_tasks = set()


async def run_processing_tasks(n, *coros):
    semaphore = asyncio.Semaphore(n)

    async def sem_coro(coro):
        try:
            async with semaphore:
                return await coro
        except asyncio.CancelledError:
            logging.debug("Task was cancelled.")
            coro.close()

    tasks = []

    for coro in coros:
        task = asyncio.create_task(sem_coro(coro))
        _running_tasks.add(task)
        task.add_done_callback(_running_tasks.discard)
        tasks.append(task)

    results = []

    for task in tasks:
        with suppress(asyncio.CancelledError):
            results.append(await task)

    return results


def cancel_processing_tasks():
    logging.debug(f"Cancelling {_running_tasks} tasks...")
    for t in _running_tasks:
        if t == asyncio.current_task():
            continue
        t.cancel()


async def send_req(url, sess):
    item = await sess.get(
        url,
        impersonate="safari15_5",
        timeout=6,
    )
    logging.debug(f"Status code: {item.status_code}")

    ran = random.randint(1, 250)
    if ran == 3:
        cancel_processing_tasks()


async def make_req(url_list):
    async with requests.AsyncSession(max_clients=10000) as sess:
        await run_processing_tasks(
            60,
            *(send_req(url, sess) for url in url_list),
        )


def wrapper_for_run_cpu_bound(func, *args, **kwargs):
    new_loop = uvloop.new_event_loop()
    asyncio.set_event_loop(new_loop)
    try:
        new_loop.run_until_complete(func(*args, **kwargs))
    except asyncio.CancelledError:
        logging.debug("Asyncio task was cancelled, closing the loop.")
        new_loop.close()
    except Exception as e:
        logging.error(f"Exception in process: {e}")
        new_loop.close()


async def main():
    try:
        for x in range(1, 3):
            s = asyncio.get_running_loop().run_in_executor(
                pool_process,
                wrapper_for_run_cpu_bound,
                make_req,
                ["https://www.google.com/"] * 300,
            )
            await s
    except Exception as e:
        logging.error(f"Exception in main: {e}")


if __name__ == "__main__":
    uvloop.install()
    asyncio.run(main(), debug=True)
```

When I use version 0.5.7 and run this code and cancel_processing_tasks function is executed everything is ok, but if I change version to 0.5.9b5 and run code and cancel_processing_tasks is executed I get error ERROR:root:Exception in main: A process in the process pool was terminated abruptly while the future was running or pending. which further in my code led to segmentation fault error

**Comment by yifeikong** [comment]
Thanks for the detailed report, I have found the issue, the cancellation is not handled correctly. Fix is on the way.

**Comment by yifeikong** [comment]
See if v0.5.9b6 fixed your issue, please.
