### ISSUE TITLE
和sanic使用时会报错

### ISSUE THREAD

**Issue by alexliyu7352** [yifeikong/curl_cffi#34]
```
Exception in callback <bound method AsyncCurl.process_data of <curl_cffi.aio.AsyncCurl object at 0x7f1738a64310>>
handle: <TimerHandle AsyncCurl.process_data created at /home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py:39>
source_traceback: Object created at (most recent call last):
  File "/home/alex/pycharm-2022.3.2/plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/alex/pycharm-2022.3.2/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/alex/workspace/parse_server/main.py", line 54, in <module>
    app.run(host="0.0.0.0", port=15368, debug=True, auto_reload=True, workers=1, access_log=False)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/mixins/runner.py", line 145, in run
    self.__class__.serve(primary=self)  # type: ignore
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/mixins/runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/server/runners.py", line 155, in serve
    loop.run_forever()
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 117, in process_data
    self.socket_action(sockfd, ev_bitmask)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 113, in socket_action
    lib.curl_multi_socket_action(self._curlm, sockfd, ev_bitmask, running_handle)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 39, in timer_function
    async_curl.timer = async_curl.loop.call_later(
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 251, in uvloop.loop.TimerHandle._run
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 117, in process_data
    self.socket_action(sockfd, ev_bitmask)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 113, in socket_action
    lib.curl_multi_socket_action(self._curlm, sockfd, ev_bitmask, running_handle)
TypeError: initializer for ctype 'void *' must be a cdata pointer, not NoneType
Exception in callback <bound method AsyncCurl.process_data of <curl_cffi.aio.AsyncCurl object at 0x7f1738a642b0>>
handle: <TimerHandle AsyncCurl.process_data created at /home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py:39>
source_traceback: Object created at (most recent call last):
  File "/home/alex/pycharm-2022.3.2/plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/alex/pycharm-2022.3.2/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/alex/workspace/parse_server/main.py", line 54, in <module>
    app.run(host="0.0.0.0", port=15368, debug=True, auto_reload=True, workers=1, access_log=False)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/mixins/runner.py", line 145, in run
    self.__class__.serve(primary=self)  # type: ignore
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/mixins/runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/server/runners.py", line 155, in serve
    loop.run_forever()
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 117, in process_data
    self.socket_action(sockfd, ev_bitmask)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 113, in socket_action
    lib.curl_multi_socket_action(self._curlm, sockfd, ev_bitmask, running_handle)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 39, in timer_function
    async_curl.timer = async_curl.loop.call_later(
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 251, in uvloop.loop.TimerHandle._run
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 117, in process_data
    self.socket_action(sockfd, ev_bitmask)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 113, in socket_action
    lib.curl_multi_socket_action(self._curlm, sockfd, ev_bitmask, running_handle)
TypeError: initializer for ctype 'void *' must be a cdata pointer, not NoneType
Exception in callback <bound method AsyncCurl.process_data of <curl_cffi.aio.AsyncCurl object at 0x7f1738a64f40>>
handle: <TimerHandle AsyncCurl.process_data created at /home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py:39>
source_traceback: Object created at (most recent call last):
  File "/home/alex/pycharm-2022.3.2/plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/alex/pycharm-2022.3.2/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/alex/workspace/parse_server/main.py", line 54, in <module>
    app.run(host="0.0.0.0", port=15368, debug=True, auto_reload=True, workers=1, access_log=False)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/mixins/runner.py", line 145, in run
    self.__class__.serve(primary=self)  # type: ignore
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/mixins/runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/server/runners.py", line 155, in serve
    loop.run_forever()
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 98, in _force_timeout
    self.socket_action(CURL_SOCKET_TIMEOUT, CURL_POLL_NONE)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 113, in socket_action
    lib.curl_multi_socket_action(self._curlm, sockfd, ev_bitmask, running_handle)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 39, in timer_function
    async_curl.timer = async_curl.loop.call_later(
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 251, in uvloop.loop.TimerHandle._run
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 117, in process_data
    self.socket_action(sockfd, ev_bitmask)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 113, in socket_action
    lib.curl_multi_socket_action(self._curlm, sockfd, ev_bitmask, running_handle)
TypeError: initializer for ctype 'void *' must be a cdata pointer, not NoneType
Exception in callback <bound method AsyncCurl.process_data of <curl_cffi.aio.AsyncCurl object at 0x7f1738a64f40>>
handle: <TimerHandle AsyncCurl.process_data created at /home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py:39>
source_traceback: Object created at (most recent call last):
  File "/home/alex/pycharm-2022.3.2/plugins/python/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/alex/pycharm-2022.3.2/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/alex/workspace/parse_server/main.py", line 54, in <module>
    app.run(host="0.0.0.0", port=15368, debug=True, auto_reload=True, workers=1, access_log=False)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/mixins/runner.py", line 145, in run
    self.__class__.serve(primary=self)  # type: ignore
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/mixins/runner.py", line 578, in serve
    serve_single(primary_server_info.settings)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/server/runners.py", line 206, in serve_single
    serve(**server_settings)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/sanic/server/runners.py", line 155, in serve
    loop.run_forever()
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 117, in process_data
    self.socket_action(sockfd, ev_bitmask)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 113, in socket_action
    lib.curl_multi_socket_action(self._curlm, sockfd, ev_bitmask, running_handle)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 39, in timer_function
    async_curl.timer = async_curl.loop.call_later(
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 251, in uvloop.loop.TimerHandle._run
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 117, in process_data
    self.socket_action(sockfd, ev_bitmask)
  File "/home/alex/workspace/parse_server/venv/lib/python3.8/site-packages/curl_cffi/aio.py", line 113, in socket_action
    lib.curl_multi_socket_action(self._curlm, sockfd, ev_bitmask, running_handle)
TypeError: initializer for ctype 'void *' must be a cdata pointer, not NoneType
```

**Comment by yifeikong** [comment]
你好，能不能把相关代码也贴一下，我修了也好加个单元测试

**Comment by alexliyu7352** [comment]
这个代码有些多.
但是你测试应该很好测试的.
使用sanic框架, 随便添加一个view.
然后里面使用你的requests.AsyncSession()就会发现请求能正常完成, 但是等待1-2秒后, 就大量的报错了.


@app.get("/test")
async def async_main(request):
    async with requests.AsyncSession() as s:
        r = await s.get("https://httpbin.org/headers", timeout=30)
    print(r.text)
    return json({"test": "test"})



Yifei Kong ***@***.***> 于2023年3月30日周四 13:56写道：

**Comment by alexliyu7352** [comment]
感谢大佬.

另外, 一段时间会出现

```
Traceback (most recent call last):
  File "/opt/parse_server/.venv/lib/python3.9/site-packages/curl_cffi/requests/session.py", line 391, in request
    c.perform()
  File "/opt/parse_server/.venv/lib/python3.9/site-packages/curl_cffi/curl.py", line 187, in perform
    self._check_error(ret, action="perform")
  File "/opt/parse_server/.venv/lib/python3.9/site-packages/curl_cffi/curl.py", line 80, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 35, Reason: 'BoringSSL SSL_connect: SSL_ERROR_SYSCALL in connection to xxxx.com:443 '

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/parse_server/apps/four_tv/helper.py", line 428, in get_hls
    stream_info = await self.get_stream_m3u8(channel_id, asset_id, quality, use_third_api, proxy)
  File "/opt/parse_server/apps/four_tv/helper.py", line 342, in get_stream_m3u8
    index_content = await self.async_get(index_m3u8_uri, proxy)
  File "/opt/parse_server/apps/four_tv/helper.py", line 205, in async_get
    resp = await app_instance.loop.run_in_executor(app_instance.ctx.threads, task)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/parse_server/.venv/lib/python3.9/site-packages/curl_cffi/requests/__init__.py", line 43, in request
    return s.request(
  File "/opt/parse_server/.venv/lib/python3.9/site-packages/curl_cffi/requests/session.py", line 393, in request
    raise RequestsError(e)
curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 35, Reason: 'BoringSSL SSL_connect: SSL_ERROR_SYSCALL in connection to xxxx.com '

```

**Comment by yifeikong** [comment]
这个看起来是 SSL 的问题啊。你可以看下是否多次添加了 impersonate 参数，以及这个值的变化是否会引起你这个错误。如果还不行的话，像这种抛出的错误有 curl 错误码的问题，那就应该是目标网站或者网络的问题了，也有可能就是人家的某种反爬措施。

我搜了下「BoringSSL SSL_connect: SSL_ERROR_SYSCALL in connection」网上还是又不少同样问题的，你可以参考下。

**Comment by alexliyu7352** [comment]
我在跟踪下
