### ISSUE TITLE
Pyinstaller Packing problem

### ISSUE THREAD

**Issue by Hn-zqz** [yifeikong/curl_cffi#5]
Thanks for this project!
I found a packaging problem with Pyinstaller
Here is my example code
```
from curl_cffi import requests
r = requests.get("https://www.zoopla.co.uk/to-rent/branch/johns-and-co-nine-elms-london-68981", impersonate="chrome101")
print(r.text)
```

It works fine
When I package it with pyinstaller

```
pyinstaller -F example.py
```

This error occurred at runtime
```
Traceback (most recent call last):
  File "ProjectTb\cffi_test\Test.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "curl_cffi\__init__.py", line 9, in <module>
ModuleNotFoundError: No module named '_cffi_backend'
[13448] Failed to execute script 'Test' due to unhandled exception!
```
Sometimes they report it wrong
```
curl_cffi.CurlError: Failed to perform, ErrCode: 77, Reason: error setting certificate verify locations:CAfile: C:\Us
ers\25605\AppData\Local\Temp\_MEI30202\curl_cffi cacert.pem CApath: none
```

**Comment by yifeikong** [comment]
The reason is that the cffi lib and the cert file were not included in your package. You can mannually add them by the following options:

    pyinstaller -F .\example.py --hidden-import=_cffi_backend --collect-all curl_cffi

**Comment by Hn-zqz** [comment]
So here we go again with the previous example and this time I'm running it in Windows 11 but this time the error is different
``
Traceback (most recent call last):
  File "ProjectTb\ZooplaGUI20230514\test.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "curl_cffi\__init__.py", line 32, in <module>
ImportError: DLL load failed: 找不到指定的模块。
[3932] Failed to execute script 'test' due to unhandled exception!
``
I found this error during the packing process and I don't know if this is the cause
``
327 WARNING: lib not found: libcurl-cbb416caa1dd01638554eab3f38d682d.dll dependency of c:\users\25605\appdata\local\programs\python\python37\lib\site-packages\curl_cffi\_wrapper.pyd
``

**Comment by yifeikong** [comment]
Please see if #48 fixes your issue.
