### ISSUE TITLE
How can I use socks proxy in Session?

### ISSUE THREAD

**Issue by BhardwajAnshul** [yifeikong/curl_cffi#54]
When I am tring to update the session proxies to the following:

            
            proxies = {
            'http': 'socks5://127.0.0.1:9150',
            'https': 'socks5://127.0.0.1:9150',
            }
            session.proxies.update(proxies=proxies)

            
Following is the error I am getting:

    Traceback (most recent call last):
      File "/Users/anshul/heystack/scraper/api_scraper/dev/api_scraper.py", line 623, in <module>
        response = scraper.browser.get('https://ipinfo.io/json')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/anshul/miniconda3/envs/main/lib/python3.11/site-packages/curl_cffi/requests/session.py", line 369, in request
        req, buffer, header_buffer = self._set_curl_options(
                                     ^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/anshul/miniconda3/envs/main/lib/python3.11/site-packages/curl_cffi/requests/session.py", line 247, in _set_curl_options
        if proxies["https"] is not None:
           ~~~~~~~^^^^^^^^^
    KeyError: 'https'

**Comment by yifeikong** [comment]
> session.proxies.update(proxies=proxies)

By this, you are setting proxies as `{"proxies": {"http": ..., "https":...}}`. I think you mean:

    session.proxies.update(**proxies)
