### ISSUE TITLE
KeyboardInterrupt is not working as intended.

### ISSUE THREAD

**Issue by BhardwajAnshul** [yifeikong/curl_cffi#64]
during KeyboardInterrupt, RequestsError is also being raised.

`RequestsError(Failed to perform, ErrCode: 23, Reason: 'Failure writing output to destination') error occurred`

**Comment by yifeikong** [comment]
More context please? like the stacktrace.

**Comment by BhardwajAnshul** [comment]
If you press Ctrl + C, you would expect the script to stop and raise a KeyboardInterrupt error. However, when you do this, curl_cffi also raises a RequestsError. This error includes messages such as "Failed to write output" or "Failed to write headers".

When pressing Ctrl + C, it is expected that the script should raise a KeyboardInterrupt error, not a RequestsError.

Also Can you please let me know when will the support for chrome 112 or chrome 113 will be added.

**Comment by Kangaroux** [comment]
Python 3.13.7
curl_cffi 0.13.0

```python
try:
  curl_cffi.get(...)
except Exception:
  logger.exception("request failed")
```

CTRL+C during a request raises `KeyboardInterrupt` but gets swallowed and raised as `curl_cffi.requests.exceptions.RequestException`:

```python
Exception ignored from cffi callback <function buffer_callback at 0x7573203c79c0>:
Traceback (most recent call last):
  File "/app/.venv/lib/python3.13/site-packages/curl_cffi/curl.py", line 100, in buffer_callback
    @ffi.def_extern()
KeyboardInterrupt: 
Sep 17 15:40:47.121 ERROR ***.py:212 > request failed
Traceback (most recent call last):
  File "/app/.venv/lib/python3.13/site-packages/curl_cffi/requests/session.py", line 640, in request
    c.perform()
    ~~~~~~~~~^^
  File "/app/.venv/lib/python3.13/site-packages/curl_cffi/curl.py", line 365, in perform
    self._check_error(ret, "perform")
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.13/site-packages/curl_cffi/curl.py", line 187, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (23) Failure writing output to destination, passed 13 returned 0. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/***.py", line 210, in request_with_retry
    return self.request(params, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/app/***.py", line 174, in request
    resp = curl_cffi.get(
        "[redacted url]",
    ...<4 lines>...
        **kwargs,
    )
  File "/app/.venv/lib/python3.13/site-packages/curl_cffi/requests/__init__.py", line 143, in get
    return request(method="GET", url=url, **kwargs)
  File "/app/.venv/lib/python3.13/site-packages/curl_cffi/requests/__init__.py", line 135, in request
    return s.request(method=method, url=url, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.13/site-packages/curl_cffi/requests/session.py", line 647, in request
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.RequestException: Failed to perform, curl: (23) Failure writing output to destination, passed 13 returned 0. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
```

**Comment by Limyx826** [comment]
Add on this, on another project with curl_cffi as dependency the below error will show up when inputting keyboard interrupt. 
```python
Exception ignored from cffi callback <function buffer_callback at 0x000002231F524720>:
Traceback (most recent call last):
  File "X:\Lib\site-packages\curl_cffi\curl.py", line 125, in buffer_callback
    @ffi.def_extern()
KeyboardInterrupt:
[warning] (HttpError: RequestException: Failed to perform, curl: (23) Failure writing output to destination, passed 13 returned 0. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.)
```

**Comment by Limyx826** [comment]
If curl_cffi not respecting keyboard interrupt, it will be a big problem for debugging and normal operation.
