### ISSUE TITLE
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 56

### ISSUE THREAD

**Issue by WFWFDSF24** [yifeikong/curl_cffi#67]
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 56

**Comment by WFWFDSF24** [comment]
Traceback (most recent call last):
  File "J:\anaconda3\envs\python_spider\lib\site-packages\curl_cffi\requests\session.py", line 391, in request
    c.perform()
  File "J:\anaconda3\envs\python_spider\lib\site-packages\curl_cffi\curl.py", line 191, in perform
    self._check_error(ret, action="perform")
  File "J:\anaconda3\envs\python_spider\lib\site-packages\curl_cffi\curl.py", line 84, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 56, Reason: 'Proxy CONNECT aborted'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:/python_spider/funcaptcha/myclient.py", line 11, in <module>
    print("chrome110:", s.get("https://tls.browserleaks.com/json",proxies=proxies,headers=headers, verify=False).json().get("ja3_hash"))
  File "J:\anaconda3\envs\python_spider\lib\site-packages\curl_cffi\requests\session.py", line 393, in request
    raise RequestsError(e)
curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 56, Reason: 'Proxy CONNECT aborted'

**Comment by yifeikong** [comment]
It seems like a proxy problem, could you please try another proxy?

**Comment by WFWFDSF24** [comment]
i use the cow-proxy，but when i use the request it work normally

**Comment by zuiailaoda** [comment]
> 
 I am experiencing the same error even when using a proxy IP with a username and password.

**Comment by zuiailaoda** [comment]
![image](https://github.com/yifeikong/curl_cffi/assets/43024499/fb4e9940-3c70-40b6-abd0-6849b1b7e382)

**Comment by yifeikong** [comment]
Close as stale, open another issue if the latest version is still not working for you
