### ISSUE TITLE
AsyncSession does not work on Windows platforms.

### ISSUE THREAD

**Issue by MooshiMochi** [yifeikong/curl_cffi#70]
```py
import asyncio
from curl_cffi import requests

URL = "https://reaperscans.com/comics/2995-perfect-surgeon"


async def main():
    async with requests.AsyncSession(impersonate="chrome101") as s:
        r = await s.get(URL)
        print(r.text)
        print(r.status_code)


if __name__ == "__main__":

    asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())

    asyncio.run(main())
```

I ran this code. I have python 3.11.4 and curl_cffi 0.5.6 installed

This is the error I got:

```py
Exception ignored from cffi callback <function socket_function at 0x000001F728227BA0>:
Traceback (most recent call last):
  File "C:\Users\rchir\OneDrive\Desktop\GitProjects\ManhwaUpdatesBot\.venv\Lib\site-packages\curl_cffi\aio.py", line 62, in socket_function
    loop.add_reader(sockfd, async_curl.process_data, sockfd, CURL_CSELECT_IN)
  File "C:\Users\rchir\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 530, in add_reader
    raise NotImplementedError
NotImplementedError: 
Exception ignored from cffi callback <function socket_function at 0x000001F728227BA0>:
Traceback (most recent call last):
  File "C:\Users\rchir\OneDrive\Desktop\GitProjects\ManhwaUpdatesBot\.venv\Lib\site-packages\curl_cffi\aio.py", line 68, in socket_function
    async_curl._sockfds.remove(sockfd)
KeyError: 644
Exception ignored from cffi callback <function socket_function at 0x000001F728227BA0>:
Traceback (most recent call last):
  File "C:\Users\rchir\OneDrive\Desktop\GitProjects\ManhwaUpdatesBot\.venv\Lib\site-packages\curl_cffi\aio.py", line 65, in socket_function
    loop.add_writer(sockfd, async_curl.process_data, sockfd, CURL_CSELECT_OUT)
  File "C:\Users\rchir\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 536, in add_writer
    raise NotImplementedError
NotImplementedError: 
Exception ignored from cffi callback <function socket_function at 0x000001F728227BA0>:
Traceback (most recent call last):
  File "C:\Users\rchir\OneDrive\Desktop\GitProjects\ManhwaUpdatesBot\.venv\Lib\site-packages\curl_cffi\aio.py", line 62, in socket_function
    loop.add_reader(sockfd, async_curl.process_data, sockfd, CURL_CSELECT_IN)
  File "C:\Users\rchir\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 530, in add_reader
    raise NotImplementedError
NotImplementedError: 
```

**Comment by yifeikong** [comment]
Accroding to the [docs](https://docs.python.org/3/library/asyncio-platforms.html#windows):

> Changed in version 3.8: On Windows, [ProactorEventLoop](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.ProactorEventLoop) is now the default event loop.
> The [loop.add_reader()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.add_reader) and [loop.add_writer()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.add_writer) methods are not supported.

You can use the SelectorEventLoop instead.

```python
import sys, asyncio

if sys.version_info >= (3, 8) and sys.platform.lower().startswith("win"):
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

**Comment by MooshiMochi** [comment]
O, thanks, it worked!

**Comment by MooshiMochi** [comment]
Think you should implement this into the library by default if possible tho!

**Comment by T-256** [comment]
Anyway to support ProactorEventLoop?
I found https://www.tornadoweb.org/en/latest/_modules/tornado/platform/asyncio.html patches
And example implementation at https://github.com/zeromq/pyzmq/pull/1524
Can we have the same patch in curl-cffi?

**Comment by yifeikong** [comment]
Cool, could you please submit a PR?

**Comment by T-256** [comment]
Yes, I'll work on it.

**Comment by yifeikong** [comment]
Thanks to @T-256, this is no longer an issue, no need to change loop since v0.6.0
