### ISSUE TITLE
how to solove this question ???

### ISSUE THREAD

**Issue by Charles-Hello** [yifeikong/curl_cffi#78]
```
from curl_cffi import requests


headers = {
    'cookie': 'pin=1;',
    'user-agent': 'JD4iPhone/167774 (iPhone; iOS 14.6; Scale/2.00)',
    'content-type': 'application/json',
    'accept-language': 'zh-Hans-CN;q=1, en-CN;q=0.9',
}

data = 'lmt=0&body=%7B%22action%22%3A%22to%22%2C%22to%22%3A%22https%253A%252F%252Fcarry.m.jd.com%252FbabelDiy%252FZeus%252F3KSjXqQabiTuD1cJ28QskrpWoBKT%252Findex.html%253FbabelChannel%253D121%22%7D'

sign = "st=1687759001409&sign=eced209ab189039cb4b7fe5a145620ad&sv=111"

print(sign)

response = requests.post(
    f'https://api.m.jd.com/client.action?functionId=genToken&lmt=0&clientVersion=11.2.2&build=98247&client=android&partner=huawei&oaid=b50f99bb238ee85b&eid=eidAe613812220s54zzbCO0oQ3qYYiWCDagnkOM83JG2xJv3bHHjzEPljqlnnfR9JS4zQm455baKi8MgUvmDZMEM7yoCBoqVGcwVm6E9OL04gYjhQec2&sdkVersion=33&lang=zh_CN&harmonyOs=0&networkType=wifi&ef=1&ep=%7B%22hdid%22%3A%22JM9F1ywUPwflvMIpYPok0tt5k9kW4ArJEU3lfLhxBqw%3D%22%2C%22ts%22%3A1687712539414%2C%22ridx%22%3A-1%2C%22cipher%22%3A%7B%22area%22%3A%22CJvpCJY1DV8zCNu3XzK%3D%22%2C%22d_model%22%3A%22CtSmDNOyCJPLGm%3D%3D%22%2C%22wifiBssid%22%3A%22dW5hbw93bq%3D%3D%22%2C%22osVersion%22%3A%22CJC%3D%22%2C%22d_brand%22%3A%22WQvrb21f%22%2C%22screen%22%3A%22CtS4CMenCNqm%22%2C%22uuid%22%3A%22CzTvDtTsENS3CwVtYzK5Cm%3D%3D%22%2C%22aid%22%3A%22CzTvDtTsENS3CwVtYzK5Cm%3D%3D%22%2C%22openudid%22%3A%22CzTvDtTsENS3CwVtYzK5Cm%3D%3D%22%7D%2C%22ciphe\nrtype%22%3A5%2C%22version%22%3A%221.2.0%22%2C%22appname%22%3A%22com.jingdong.app.mall%22%7D&{sign}',
    data=data,
    impersonate="chrome101"
)

print(response.text)
```

```
Traceback (most recent call last):
  File "C:\Users\a1140\Desktop\pybot\demo\指纹tls\testtls.py", line 19, in <module>
    response = requests.post(
               ^^^^^^^^^^^^^^
  File "C:\Users\a1140\AppData\Local\Programs\Python\Python311\Lib\site-packages\curl_cffi\requests\__init__.py", line 46, in request
    return s.request(
           ^^^^^^^^^^
  File "C:\Users\a1140\AppData\Local\Programs\Python\Python311\Lib\site-packages\curl_cffi\requests\session.py", line 438, in request
    raise RequestsError(e)
curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 3, Reason: ''
```

**Comment by yifeikong** [comment]
Please check the [libcurl error page](https://curl.se/libcurl/c/libcurl-errors.html) first. In your case, there is a `\n` in the url.

**Comment by Charles-Hello** [comment]
好滴！！谢谢啦！搞定了
